# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    #- name: SonarCloud Scan
      #uses: SonarSource/sonarcloud-github-action@v3.1.0
      #env:
          #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #with:
          #projectKey: lmofor_vrconseiltest
          #organization: lmofor
          #scanner-mode: sarif
    - name: Download SonarScanner for Ant
      uses: actions/download-artifact@v2
      with:
        name: sonar-scanner
    - name: Set up environment variables
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Configure SonarScanner
      run: |
        echo "sonar.projectKey=${{ github.repository }}" > sonar-project.properties
        echo "sonar.organization=${{ github.repository_owner }}" >> sonar-project.properties
        echo "sonar.host.url=https://sonarcloud.io" >> sonar-project.properties
    - name: Execute SonarScanner
      run: ./sonar-scanner
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
